camunda/camunda-deployment-references

.github/workflows/aws_ec2_tests.yml
due to the runtime can and will overlap with nightly cleanup
=> chore: change cron for ec2 test

.github/workflows/aws_ec2_golden.yml, .github/workflows/aws_ec2_tests.yml
Adds asdf cache to speed up the installation. Only the first installation where something changed takes longer.
See Example run here: https://github.com/camunda/infraex-common-config/pull/163
=> feat: add asdf tool cache

.lint/trivy/trivy-scan.sh, .lint/trivy/trivy.yaml, .pre-commit-config.yaml, .tool-versions, .trivyignore, aws/ec2/terraform/security.tf, aws/ec2/test/golden/tfplan.json
Source issue: https://github.com/camunda/team-infrastructure-experience/issues/37
Extending the scope of the above issue to this repository as well, implementing a trivy scan of terraform files within was directory, excluding fixtures (formerly tfsec).
Issues are ignored for now and listed in .trivyignore
=> lint(pre-commit): add trivy check on terraform directory (issues ignored)

aws/rosa-hcp-dual-region/procedure/camunda/8.7/helm-values/values-base.yml
based on feedback, we should align the elasticsearch master count with the helm chart.
=> chore: bump elasticsearch instances

.github/workflows/aws_ec2_golden.yml, .github/workflows/aws_openshift_rosa_hcp_single_region_golden.yml, aws/openshift/rosa-hcp-single-region/test/golden/tfplan-golden.json
We should always execute the PR diff message otherwise you will miss out on it actually succeeding.
Related to - https://github.com/camunda/camunda-deployment-references/pull/144#issuecomment-2729069928
Had a meeting inbetween 😓
=> fix: always post diff if golden triggered

aws/openshift/rosa-hcp-dual-region/procedure/helm-values/values-base.yml
the emptyDir situation was fixed upstream in the Bitnami Chart, which the 11.2.2 Camunda Helm chart is using.
=> fix: remove empty-dir addition since its fixed upstream

.github/actions/aws-aurora-manage-cluster/README.md, .github/actions/aws-aurora-manage-cluster/action.yml, .github/actions/aws-eks-manage-cluster/README.md, .github/actions/aws-eks-manage-cluster/action.yml, .github/actions/aws-opensearch-manage-cluster/README.md, .github/actions/aws-opensearch-manage-cluster/action.yml, aws/kubernetes/eks-single-region-irsa/procedure/get-your-copy.sh, aws/kubernetes/eks-single-region/procedure/get-your-copy.sh, aws/openshift/rosa-hcp-single-region/procedure/get-your-copy.sh
Removal of some leftover `merge-branch` names to `main`.
=> chore: rename merge-branch occurences to main

.github/actions/aws-openshift-rosa-hcp-single-region-cleanup/action.yml, .github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml, .github/actions/aws-utility-action/action.yml, .github/workflows/internal_openshift_artifact_rosa_versions.yml, MAINTENANCE.md
This PR enforce usage of the /tmp directory to prevent any leftover in the current project when we download cli & artifacts
Related to https://github.com/camunda/infraex-common-config/pull/212
=> fix: use /tmp as working directory to download archives

.github/actions/internal-triage-skip/action.yml
maybe it was working implicitly already, I just want to have it explicit that it should do those checks on PRs otherwise simply always return false.
Not sure it was tried prior or not with any other event but PR, want to avoid failing schedules.
Tried it out without the fix since I was using `push` trigger on my EKS workings. (fails)
```
Prepare all required actions
Run ./.github/actions/internal-triage-skip
Run workflow_file_name=$(echo "camunda/camunda-deployment-references/.github/workflows/aws_kubernetes_eks-single_region_tests.yml@refs/heads/infraex-64[2](https://github.com/camunda/camunda-deployment-references/actions/runs/14084609563/job/39445279393#step:3:2)" | sed 's/@.*//')
workflow_file_name=aws_kubernetes_eks-single_region_tests
jq: error (at …
```
=> fix: triage should always return false on non PR

justfile
related to https://github.com/camunda/camunda-deployment-references/actions/runs/14440234251/job/40488572608
The else didn't need a change and affected ec2, rest was fine.
Related runs:
- EC2 - https://github.com/camunda/camunda-deployment-references/actions/runs/14443636761 ✅ 
- EKS - https://github.com/camunda/camunda-deployment-references/actions/runs/14443647386 ✅ 
- ROSA - dual - https://github.com/camunda/camunda-deployment-references/actions/runs/14443649136 ✅ 
- ROSA - single - https://github.com/camunda/camunda-deployment-references/actions/runs/14443651016 ✅
=> fix: generation of golden files

.github/actions/aws-eks-manage-cluster/README.md, .github/actions/aws-eks-manage-cluster/action.yml, .github/actions/aws-kubernetes-eks-single-region-create/README.md, .github/actions/aws-kubernetes-eks-single-region-create/action.yml, aws/kubernetes/eks-single-region-irsa/cluster.tf, aws/kubernetes/eks-single-region/cluster.tf, aws/modules/eks-cluster/README.md, aws/modules/eks-cluster/variables.tf, aws/modules/eks-cluster/vpc.tf, aws/modules/fixtures/fixtures.default.eks.tfvars
related to https://github.com/camunda/team-infrastructure-experience/issues/539
- Adds single nat gateway option for EKS (false by default), so preserving the old behaviour
- For the tests we're overwriting it and just using a single nat to save on IPs
- adjusted the IP check to properly reflect usage
Skipped module tests for the rerun as they passed and didn't change based on the fix for the eks single-region stuff.
- https://github.com/camunda/camunda-deployment-references/actions/runs/14464748096
- https://github.com/camunda/camunda-deployment-references/actions/runs/14464748108
- https://github.com/camunda/camunda-deployment-references/actions/runs/14466534168
=> chore: add single nat option for EKS

generic/kubernetes/single-region/procedure/chart-env.sh, generic/openshift/dual-region/procedure/chart-env.sh, generic/openshift/single-region/procedure/chart-env.sh
fixes https://github.com/camunda/camunda-deployment-references/pull/232
adding `versioning` will result in Renovate not processing it as `0.0.0....` != `12....` + added release-duty comment to update.
=> chore: add release-duty and versioning to helm chart renovate

.github/workflows/aws_modules_eks_rds_os_tests.yml
currently it was default to a different region (eu-west-2), while the suggested bucket is `eu-central-1`.
Resulting in the cleanup not kicking in since it was looking in the wrong bucket. 
And scheduled cleanup wouldn't find the resources either, till ultimately nightly cleanup would remove the resources.
- Added the env variable to set the bucket region correctly.
Should definitely help also with renovate as those resources would be blocking a couple of IPs as well till nightly nuke.
Will afterwards port to 8.7.
=> fix: add TF_STATE_BUCKET_REGION value for the s3 bucket

.github/workflows/aws_modules_eks_rds_os_tests.yml
backport of https://github.com/camunda/camunda-deployment-references/pull/332
=> fix: add TF_STATE_BUCKET_REGION value for the s3 bucket (#332)

.github/actions/aws-kubernetes-eks-single-region-cleanup/scripts/destroy-clusters.sh
small typo, we call it `resources`, `groups`, and `clusters` 😅 , depending on the context.
Didn't see it in the first review.
Tried it out locally, works now again correctly.
=> fix: eks cluster cleanup, typo

.github/actions/aws-kubernetes-eks-single-region-cleanup/action.yml, .github/workflows-config/workflow-scheduler.yml, .github/workflows/aws_kubernetes_eks_single_region_cleanup.yml
Before it was cleaned up by the daily cleanup.
This is focused on the EKS ref arch and was missing so far.
Also makes it easier to trigger manually afterwards, similar to our other cleanups.
Will afterwards be backported to 8.7.
For simplicity, did not do a dynamic matrix but just cleanup all.
Example execution:
https://github.com/camunda/camunda-deployment-references/actions/runs/14666718799
=> chore: add eks focused cleanup job

.github/actions/internal-camunda-chart-tests/action.yml
fixes an issue that in case of dual-region openshift triggered both port-forwardings and failed.
=> fix: skip single in dual-region zeebe check

generic/kubernetes/single-region/tests/helm-values/identity.yml
A quick clean up for any reference to the old `camunda-platform-alpha` dir.
Related to: https://github.com/camunda/team-distribution/issues/499
=> chore: rename chart dir from alpha to 8.7

.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
related to retry error - https://github.com/camunda/camunda-deployment-references/actions/runs/15110208195/job/42471369892
We were deleting a MultiClusterSet but trying to add finalizers to a different resource that didn't need it yet. 
Backport
=> fix: rosa dual-reg retry finalizer duplicate removal

.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
related to https://github.com/camunda/camunda-deployment-references/pull/465
Backport to 8.7
=> fix: rosa dual-reg retry finalizer duplicate removal (#465)

.github/actions/azure-kubernetes-aks-single-region-cleanup/action.yml, .github/workflows-config/workflow-scheduler.yml, .github/workflows/aws_kubernetes_eks_single_region_daily_cleanup.yml, .github/workflows/azure_kubernetes_aks_single_region_cleanup.yml, .github/workflows/azure_kubernetes_aks_single_region_daily_cleanup.yml
precaution in case the token has expired as otherwise the retry will fail as well.
Related to [failed report](https://camunda.slack.com/archives/C076N4G1162/p1747794617662809).
The Slack thread linked above contains more alternative approaches.
For now the quick and easy one to re-authenticate before the retry.
On average it needs ~ 10 minutes to teardown everything, if it can't manage to delete everything within 60 then the extended token would not be able to solve that either and anyway the retry would be the way to go forward.
Backport - file rename of EKS daily cleanup job.
=> fix: login to Azure again before retry

.github/workflows/aws_kubernetes_eks_single_region_daily_cleanup.yml
* fix: login to Azure again before retry
precaution in case the token has expired as otherwise the retry will fail as well
* fix: rename workflows and add upload logs for azure
backport of https://github.com/camunda/camunda-deployment-references/pull/476
Real change is the filename change.
=> fix: rename eks daily cleanup worklow (#476)

.github/actions/aws-aurora-manage-cluster/action.yml, .github/actions/aws-eks-manage-cluster/action.yml, .github/actions/aws-kubernetes-eks-single-region-create/action.yml, .github/actions/aws-opensearch-manage-cluster/action.yml, .github/actions/aws-openshift-rosa-hcp-dual-region-create/action.yml, .github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml, .github/actions/azure-kubernetes-aks-single-region-create/action.yml, .github/workflows/aws_kubernetes_eks_single_region_tests.yml, .github/workflows/aws_modules_eks_rds_os_tests.yml
Sanitizes the tags to comply with AWS allowed characters.
I've also applied the same logic to Azure. It didn't fail but it also didn't run with `[bot]`, so just to be on the safe side.
Input:
```
{
"ci-run-id": "15148822809",
"ci-run-number": "244",
"ci-workflow": "Tests - Integration - AWS EKS Cluster with an AuroraDB and OpenSearch creation and destruction",
"ci-actor": "infraex-misc[bot]",
"ci-ref": "refs/pull/472/merge",
"ci-commit": "e578c9488c247fc62ef23b62d776671db5686352",
"ci-repo": "camunda/camunda-deployment-references",
"ci-event": "pull_request"
}
```
Output sanitzed:
```
{"ci-run-id"="15148822809", "ci-run-number"="244", "ci-workflow"="Tests - Integration - AWS EKS Cluster with an AuroraDB and OpenSearch creation and destruction", "ci-actor"="infraex-misc-bot", …
```
=> fix: sanatize tags

generic/kubernetes/single-region/procedure/chart-env.sh, generic/openshift/single-region/helm-values/operate-route.yml, generic/openshift/single-region/helm-values/tasklist-route.yml, generic/openshift/single-region/procedure/chart-env.sh
backport of https://github.com/camunda/camunda-deployment-references/pull/508 for 8.7
// note to self, fix renovate for the helm chart.
=> Backport 8.7 tls cluster membership if domain

aws/openshift/rosa-hcp-dual-region/procedure/export_environment_prerequisites.sh, generic/openshift/single-region/helm-values/operate-route.yml, generic/openshift/single-region/helm-values/tasklist-route.yml, generic/openshift/single-region/procedure/chart-env.sh
backport of https://github.com/camunda/camunda-deployment-references/pull/508 for 8.6
// note to self, fix renovate for the helm chart.
=> Backport 8.6 tls cluster membership if domain

.github/workflows/aws_openshift_rosa_hcp_single_region_daily_cleanup.yml
backport of https://github.com/camunda/camunda-deployment-references/pull/552
=> fix: reduce false positive alerts for cleanup jobs (#552) [ci skip]

.github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml, .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
related to [slack](https://camunda.slack.com/archives/C076N4G1162/p1750048595082579) and [errored job](https://github.com/camunda/camunda-deployment-references/actions/runs/15671090483).
This PR fixes two issues in the ROSA single region test:
- in case of non private cluster (no VPN) usage, it failed a step that wasn't skipped
- in case of private cluster (VPN) usage, it failed as the tags were not sanitized in case of `[bot]` users.
Run checking that the non VPN fix works:
- https://github.com/camunda/camunda-deployment-references/actions/runs/15674350221/job/44157027502?pr=610
Run that checks the VPN tag sanitization:
- https://github.com/camunda/camunda-deployment-references/actions/runs/15676228331?pr=610
=> fix: only execute vpn export step when private is enabled

.github/actions/aws-openshift-rosa-hcp-dual-region-create/action.yml, .github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml
as well as skip awk in favour of k8s supported name returnal
related to https://camunda.slack.com/archives/C076N4G1162/p1750115840775489 and https://camunda.slack.com/archives/C076N4G1162/p1750140003725549 on slack.
I simplifies the `k8s get context` by removing the awk and just return names as is from the beginning.
I could imagine that maybe with the `awk` a space is in there and the `^$` won't work. `-x` option of grep is just an alias for `^$`.
Also I added removal of the old context just in case to allow recreating it, in case it still jumps into that line.
Backport:
=> fix: rosa delete and re-create context

.github/workflows/azure_common_procedure_storageaccount_test.yml
otherwise it will clash if the workflow runs twice.
Noticed it as part of the maintenance PRs. Must have clashed with another run. (maybe scheduled)
=> fix: generate random azure rg name

.github/actions/internal-camunda-chart-tests/action.yml
small adjustment on the path, just overwrite the `.tool-versions`
Path were slightly wrong, not overwriting the right usage.
Opted in the end to overwrite the Helm Chart file instead.
tested it already in the 8.6 PR - https://github.com/camunda/camunda-deployment-references/pull/683
=> fix: copy .tool-versions to replace helm chart file

.github/renovate.json5, generic/kubernetes/single-region/procedure/export-ingress-setup-vars.sh
4.13.0 introduced a change that broke the default certificate behaviour.
They have already fixed the issue but they have yet to release a new version with the fix.
I've so far always downgraded it in the renovate PR as it broke. But sometimes it gets in after all as my commit on Monday was somehow completely removed + if pushing quickly after one another then the automerge will bypass all checks.
I've also tried in the past to close the Renovate PR but didn't do anything as we group all dependencies otherwise it would automatically ignore it from Renovate side.
This will ignore this particular version in the renovate config, so it shouldn't appear again + downgrade again.
=> chore: downgrade ingress-nginx again

.github/actions/internal-triage-skip/action.yml
triage is running almost everywhere already anyway, this way we can quickly and only once define a bit of debug info for the workflow
this includes dispatch info if available, actor, some other info
related to figuring out why concurrecny didnt work properly with renovate
I've tested this in a private repo with workflow dispatch, with and without inputs. With a PR that has labels and not.
I'd fast pass this so that this weekend the renovate PRs already include this change.
=> chore: add debug info to triage step

.github/actions/aws-aurora-manage-cluster/action.yml, .github/actions/aws-compute-ec2-single-region-create/action.yml, .github/actions/aws-kubernetes-eks-single-region-create/action.yml, .github/actions/aws-openshift-rosa-hcp-dual-region-create/action.yml, .github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml, .github/actions/azure-kubernetes-aks-single-region-create/action.yml, .github/actions/internal-terraform-drift-detect/README.md, .github/actions/internal-terraform-drift-detect/action.yml, azure/kubernetes/aks-single-region/test/golden/tfplan-golden.json, azure/modules/aks/README.md, azure/modules/aks/node_pools.tf, azure/modules/aks/variables.tf
the idea here is that since we dont run them atm longterm to at least check after the immediate apply whether there's still a drift or not
Meaning something would need to be fixed in the config, otherwise not good ux
Following workflow run shows a drift detected:
https://github.com/camunda/camunda-deployment-references/actions/runs/17120867185/job/48561204864?pr=854
Consider backporting to 8.7.
=> feat: add config flap / drift detection for tf

aws/openshift/rosa-hcp-dual-region/procedure/export_environment_prerequisites.sh, generic/openshift/single-region/procedure/chart-env.sh
Two issues in here:
1.
```
export HELM_CHART_VERSION=11.8.0
```
Will not search for version 11 but only version 12, so latest published stable version.
Adding the regex will fix it and search only for major 11 versions.
2.
```
```
The order is important, if registryUrl comes after the version it will be interpreted as part of the version.
=> fix: renovate annotation ordering to properly update helm chart

.github/workflows/azure_kubernetes_aks_single_region_tests.yml, azure/kubernetes/aks-single-region/manifests/setup-postgres-create-db.yml, generic/kubernetes/single-region/tests/helm-values/registry-harbor.yml
backport of the azure fix: https://github.com/camunda/camunda-deployment-references/pull/916
will merge after successful run.
depends on https://github.com/camunda/camunda-deployment-references/pull/921
the helm chart reference is lagging too much behind as `allowInsecure` was only introduced in 12.3 or so.
=> fix: Azure switch registry 8.7
